version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build               

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm@5
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: Deploy application to AWS
          command: |
            ssh -o StrictHostKeyChecking=no MyWebServer@ec2-3-249-190-119.eu-west-1.compute.amazonaws.com "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"project_key\"; rm -rf simpleApplication/; git clone https://github.com/GeorgeKrp/simpleApplication.git; source ~/simpleApplication/deploy.sh"
