version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - run-code:
          filters:
            branches:
              only:
                - main

jobs:
  run-code:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Run code
          command: node app.js
